-- AlterTable
ALTER TABLE `Brand` ADD COLUMN `planType` ENUM('FREE', 'PRO', 'PRO_PLUS') NOT NULL DEFAULT 'FREE',
    ADD COLUMN `subscriptionStatus` ENUM('ACTIVE', 'PENDING_PAYMENT', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `stripeCustomerId` VARCHAR(191) NULL;
